# Generated by Django 2.2.3 on 2019-08-08 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_number', models.CharField(default='0000000', max_length=50)),
                ('question', models.CharField(default='0000000', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('input', models.CharField(max_length=1000)),
                ('output', models.CharField(max_length=100)),
                ('que', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.Questions')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='0000000', max_length=250)),
                ('password', models.CharField(default='0000000', max_length=250)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='QUESTION',
        ),
        migrations.AddField(
            model_name='questions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.UserProfiles'),
        ),
    ]
