# Generated by Django 2.2.3 on 2019-09-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='qid',
            field=models.IntegerField(default=0),
        ),
    ]
