# Generated by Django 2.2.3 on 2019-08-17 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_auto_20190817_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='scoreQuestion1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='scoreQuestion2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='scoreQuestion3',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='scoreQuestion4',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='scoreQuestion5',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='scoreQuestion6',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='totalAttempts',
        ),
        migrations.CreateModel(
            name='MultipleQues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.IntegerField(verbose_name=False)),
                ('scoreQuestion', models.IntegerField(default=0)),
                ('attempts', models.IntegerField(default=0)),
                ('que', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.UserProfile')),
            ],
        ),
    ]
