# Generated by Django 2.2.3 on 2019-08-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_auto_20190825_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='correctTestCases',
            field=models.IntegerField(default=0),
        ),
    ]
