# Generated by Django 2.2.3 on 2019-09-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_userprofile_qid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='subStatus',
            field=models.CharField(default='W.A.', max_length=5),
        ),
    ]
