# Generated by Django 2.2.3 on 2019-09-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_auto_20190908_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='attempt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='subStatus',
            field=models.CharField(default='PASS', max_length=5),
        ),
    ]
