# Generated by Django 2.2.3 on 2019-08-17 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_auto_20190817_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multipleques',
            name='qid',
        ),
        migrations.AlterField(
            model_name='multipleques',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
