# Generated by Django 2.2.3 on 2019-09-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0004_auto_20190909_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='out',
            field=models.IntegerField(default=0),
        ),
    ]
