# Generated by Django 2.2.3 on 2019-08-17 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0004_auto_20190817_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multipleques',
            name='que',
        ),
    ]
