# Generated by Django 2.2.3 on 2019-08-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0005_auto_20190825_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='correctTestCasesPercentage',
            field=models.IntegerField(default=0),
        ),
    ]
