# Generated by Django 2.2.5 on 2019-09-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0005_submission_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='subStatus',
            field=models.CharField(default='NA', max_length=5),
        ),
    ]
