# Generated by Django 2.2.3 on 2019-08-18 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0006_multipleques_que'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipleques',
            name='que',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='userApp.Question'),
        ),
    ]
