# Generated by Django 2.2.3 on 2019-08-25 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0006_submission_correcttestcasespercentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='correctTestCasesPercentage',
            new_name='TestCasesPercentage',
        ),
    ]
