# Generated by Django 2.0.4 on 2019-08-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0007_auto_20190818_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
