# Generated by Django 2.2.3 on 2019-09-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0008_auto_20190831_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='timer',
            field=models.TimeField(default='00:00'),
        ),
    ]
